new

diff --git a/.github/workflows/selenium-ci.yml b/.github/workflows/selenium-ci.yml
--- a/.github/workflows/selenium-ci.yml
+++ b/.github/workflows/selenium-ci.yml
@@ -4,27 +4,42 @@ on:
   push:
     branches:
       - main
+  pull_request:
+    branches:
+      - main
+  workflow_dispatch: # Allows manual triggering
 
 jobs:
   test:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout repository
+      - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Set up JDK
+      - name: Set Up Java
         uses: actions/setup-java@v3
         with:
           distribution: 'temurin'
           java-version: '17'
 
-      - name: Navigate to project directory & install dependencies
+      - name: Cache Maven Packages
+        uses: actions/cache@v3
+        with:
+          path: ~/.m2
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
+
+      - name: Verify Project Directory
+        run: |
+          if [ ! -d "${{ github.workspace }}/RestAutomation" ]; then
+            echo "Directory not found!"
+            exit 1
+          fi
+
+      - name: Install Dependencies & Run Tests
         run: |
           cd ${{ github.workspace }}/RestAutomation
           mvn install
-
-      - name: Run Selenium tests
-        run: |
-          cd ${{ github.workspace }}/RestAutomation
-          mvn test -DsuiteXmlFile=testing.xml
+          mvn test -DsuiteXmlFile=testng.xml
